### ISSUE TITLE
Texture editing

### ISSUE THREAD

**Issue by runsrr** [Meowmaritus/DSFBX#1]
Is there chance that you can add support for texture editing for the files that DSFBX creates.
Because I keep getting errors that the g_Specular    g_Bumpmap
textures are missing but in 3ds max the textures are already added to the specular and bump but DSFBX
can't seem to read them.

**Comment by Meowmaritus** [comment]
**g_Specular**:
  * Specular channel for PTDE
  * Reflection channel for DS1R
  * It's 2 different ones so that you can import to both games at once (they have completely different specular maps)

**g_Bumpmap**:
  * Normal Map channel

**Comment by runsrr** [comment]
Thanks that helped :)
